DROP SCHEMA IF EXISTS `petsmicrodb`;

CREATE SCHEMA `petsmicrodb`;

use `petsmicrodb`;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `PET_USER`;

CREATE TABLE `PET_USER` (
  `ID` int(5) NOT NULL AUTO_INCREMENT,
  `USER_NAME` varchar(55) NOT NULL UNIQUE,
  `USER_PASSWORD` varchar(55) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;



